language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt
  - wget https://chromedriver.storage.googleapis.com/104.0.5112.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.7.1/bin
  - export CHROME_BIN=chromium-browser

env: DJANGO_SETTINGS_MODULE="vocal_trainer.settings.travis"

services:
  - postgresql
  - redis-server

script:
  - coverage run manage.py test ipa_board
  - coverage run -a manage.py test minimal_pair
#  - coverage run -a manage.py test quiz
#  - coverage run -a manage.py test user

branches:
  only:
    - dev

addons:
  chrome: stable

sudo: required

