# Generated by Django 3.1.7 on 2021-03-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleword',
            name='ipa_label',
            field=models.CharField(db_column='ipa_label', help_text='IPA word label', max_length=254, null=True, verbose_name='IPA word label'),
        ),
        migrations.AlterField(
            model_name='exampleword',
            name='label',
            field=models.CharField(db_column='label', help_text='Word label', max_length=254),
        ),
    ]
