# Generated by Django 3.1.1 on 2021-02-17 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minimal_pair', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minimalpairinformation',
            name='associated_sound_id',
            field=models.ForeignKey(db_column='associated_sound_id', help_text='Associated sound', null=True, on_delete=django.db.models.deletion.CASCADE, to='minimal_pair.minimalpairinformation'),
        ),
    ]
