# Generated by Django 3.1.7 on 2021-03-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipa_board', '0003_auto_20210318_1917'),
        ('minimal_pair', '0002_auto_20210217_1822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MinimalPairWordPhonemePlace',
            new_name='MinimalPairWordPhonemeLetters',
        ),
        migrations.RemoveField(
            model_name='minimalpairinformation',
            name='associated_sound_id',
        ),
        migrations.AddField(
            model_name='minimalpairinformation',
            name='associated_word_id',
            field=models.ForeignKey(db_column='associated_word_id', help_text='Associated sound', null=True, on_delete=django.db.models.deletion.CASCADE, to='minimal_pair.minimalpairinformation'),
        ),
        migrations.AlterField(
            model_name='minimalpaircategory',
            name='associated_phoneme',
            field=models.ForeignKey(db_column='associated_phoneme_id', help_text='Associated phoneme', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_phoneme_id', to='ipa_board.phonemeinformation', verbose_name='Associated phoneme'),
        ),
        migrations.AlterField(
            model_name='minimalpaircategory',
            name='phoneme',
            field=models.ForeignKey(db_column='phoneme_id', help_text='Phoneme', on_delete=django.db.models.deletion.CASCADE, related_name='first_phoneme_id', to='ipa_board.phonemeinformation', verbose_name='First phoneme'),
        ),
        migrations.AlterModelTable(
            name='minimalpairwordphonemeletters',
            table='minimal_pair_word_phoneme_letters',
        ),
    ]
